### ISSUE TITLE
[Bug]监听事件无法获取数据导致崩溃

### ISSUE THREAD

**Issue by CSneko** [ONFNTH/QQBot#1]
待处理
![Image_1703991419114.jpg](https://github.com/ONFNTH/QQBot/assets/135438028/d42fdf4b-964d-474c-8ff8-d32f25368e50)

![Image_1703991419217.jpg](https://github.com/ONFNTH/QQBot/assets/135438028/4586c84b-bdc6-41ca-9cc2-63e805de7754)

![Image_1703991419102.jpg](https://github.com/ONFNTH/QQBot/assets/135438028/447f4d88-d29b-430f-b16a-6cc0dc2943f5)

**Comment by fengxiangQAQ** [comment]
使用try方法修复
